let shopItemsData = [
  {
    id: "as",
    name: "Casual Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit  consectetur .",
    img: "images/img-1.jpg",
  },
  {
    id: "aa",
    name: "Office Shirt",
    price: 100,
    desc: "Lorem ipsum dolor sit  consectetur .",
    img: "images/img-2.jpg",
  },
  {
    id: "sf",
    name: "T Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit  consectetur .",
    img: "images/img-3.jpg",
  },
  {
    id: "aaa",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit  consectetur .",
    img: "images/img-4.jpg",
  },
  {
    id: "bb",
    name: "Mens Tie",
    price: 25,
    desc: "Lorem ipsum dolor sit  consectetur .",
    img: "images/img-5.png",
  },
  {
    id: "cc",
    name: "Casual shoes",
    price: 200,
    desc: "Lorem ipsum dolor sit  consectetur .",
    img: "images/img-6.png",
  },
  {
    id: "dd",
    name: "black suit",
    price: 450,
    desc: "Lorem ipsum dolor sit  consectetur .",
    img: "images/img-7.png",
  },
  {
    id: "ff",
    name: "polo shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit  consectetur .",
    img: "images/img-8.png",
  },
  {
    id: "ll",
    name: "denim shirt",
    price: 85,
    desc: "Lorem ipsum dolor sit  consectetur .",
    img: "images/img-9.png",
  },
  {
    id: "ag",
    name: "denim pants",
    price: 120,
    desc: "Lorem ipsum dolor sit  consectetur .",
    img: "images/img-10.png",
  },
  {
    id:"agd",
    name: "basic cap",
    price: 35,
    desc: "Lorem ipsum dolor sit  consectetur .",
    img: "images/img-11.png",
  },
  {
    id: "agg",
    name: "leather boots",
    price: 350,
    desc: "Lorem ipsum dolor sit  consectetur .",
    img: "images/img-12.png",
  },
];
